//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.Controls.Issues {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("F:\\git\\xam\\forms\\mx\\src\\Xamarin.Forms.ControlGallery\\issues\\Bugzilla26032.xaml")]
    public partial class Bugzilla26032 : global::Xamarin.Forms.Controls.TestContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.ListView List1;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.ListView List2;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Label Log;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(Bugzilla26032));
            List1 = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.ListView>(this, "List1");
            List2 = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.ListView>(this, "List2");
            Log = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Label>(this, "Log");
        }
    }
}
