//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.Controls {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("F:\\git\\xam\\forms\\mx\\src\\Xamarin.Forms.ControlGallery\\issues\\Issue1741.xaml")]
    public partial class Issue1741 : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Switch chkAnon;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(Issue1741));
            chkAnon = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Switch>(this, "chkAnon");
        }
    }
}
