//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.Controls.TestCasesPages {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("F:\\git\\xam\\forms\\mx\\src\\Xamarin.Forms.ControlGallery\\issues\\Issue1568.xaml")]
    public partial class Issue1568 : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.StackLayout _stackToolbar;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button _btnExit;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button _btnSelectOrg;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button _btnSelectStartInterval;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button _btnReload;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button _btnSave;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.BoxView _scheduleGrid;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.BoxView _shiftEditor;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(Issue1568));
            _stackToolbar = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.StackLayout>(this, "_stackToolbar");
            _btnExit = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "_btnExit");
            _btnSelectOrg = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "_btnSelectOrg");
            _btnSelectStartInterval = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "_btnSelectStartInterval");
            _btnReload = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "_btnReload");
            _btnSave = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "_btnSave");
            _scheduleGrid = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.BoxView>(this, "_scheduleGrid");
            _shiftEditor = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.BoxView>(this, "_shiftEditor");
        }
    }
}
