//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.Controls {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("F:\\git\\xam\\forms\\mx\\src\\Xamarin.Forms.ControlGallery\\issues\\Issue2659.xaml")]
    public partial class Issue2659 : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.StackLayout stackLayout;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button button0;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button button1;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button button2;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button button3;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(Issue2659));
            stackLayout = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.StackLayout>(this, "stackLayout");
            button0 = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "button0");
            button1 = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "button1");
            button2 = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "button2");
            button3 = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "button3");
        }
    }
}
