//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Forms.Controls {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("F:\\git\\xam\\forms\\mx\\src\\Xamarin.Forms.ControlGallery\\issues\\Issue1653v2.xaml")]
    public partial class Issue1653v2 : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.StackLayout accountDetailsStack;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.StackLayout carrierHeaderStack;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Label productNameLabel;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.StackLayout addonGroupStack;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.Button activateButton;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private global::Xamarin.Forms.ActivityIndicator checkoutRunningIndicator;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Xaml.BuildTasks.XamlG", "0.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(Issue1653v2));
            accountDetailsStack = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.StackLayout>(this, "accountDetailsStack");
            carrierHeaderStack = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.StackLayout>(this, "carrierHeaderStack");
            productNameLabel = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Label>(this, "productNameLabel");
            addonGroupStack = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.StackLayout>(this, "addonGroupStack");
            activateButton = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "activateButton");
            checkoutRunningIndicator = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.ActivityIndicator>(this, "checkoutRunningIndicator");
        }
    }
}
